### PR TITLE
 IDRUP Support 

### PR DESCRIPTION
**Pull request by m-fleury**
Sorry that it took me way too long to find the time to work on that…

Anyway, this is the rebased and squashed version of https://github.com/msoos/cryptominisat/pull/744

### CODE REVIEW

**Comment by msoos** [comment]
Wow, nice, thank you so so much! I'll review and merge today night :)

Mate

**Comment by msoos** [comment]
Wow, thank you so much!!

**Comment by msoos** [comment]
Hey hey!

It' s me from the future with some feedback :) Unfortunately, `idrup` wasn't initialized in the header, but was set as default value : `.default_value(conf.idrup)` so unless `--idrup` was given, it was set to some unknown value. Also, it seems to have assumed that `idrup` is always on, due to calling `conclude_idrup` always I think? So it seemed to have lead to segfault when it wasn't on I think :S Unfortunately, since there is no `fuzz_test.py` changeset to check whether it's correct, I'm not sure it runs/continues to run given my changes over the months :( Maybe I'll write a fuzzer for it. If I don't, I'm afraid it will be broken soon :(

Anyway, now at least FRAT is working in my development version :) I hope the above helps! Cheers and thanks again, idrup is actually really cool as an idea, it just takes time to get it into shape,

Mate

**Comment by m-fleury** [comment]
Do you want me to try to fix it or do you just want to revert the changes?

**Comment by msoos** [comment]
I already fixed it of course. Cheers,

Mate

**Comment by msoos** [comment]
Oh, if you feel like writing a fuzzer for it, that'd be nice! Did you write a fuzzer as part of the paper? In my experience, without a fuzzer, it breaks very easily and hence not really useful in the long term. Is there a fuzzer for it?

Mate

**Comment by m-fleury** [comment]
> In my experience, without a fuzzer, it breaks very easily and hence not really useful in the long term. 

Also my experience.



There is a fuzzer with the checker: https://github.com/arminbiere/idrup-check (the changes to make Cryptominisat are not public).  It is how I tested the code actually. Then I wil try to understand the fuzz_test.py.

**Comment by msoos** [comment]
Ahh I see! I mean, I'd be grateful if you integrated that into fuzz_test.py, but I understand that it's a lot of work. Up to you :)

Mate

**Pull request merged**
