### PR TITLE
Fix Boost linkage

### PR DESCRIPTION
**Pull request by Shatur**
Attempt to fix issue addressed in https://github.com/stp/stp/pull/413

### CODE REVIEW

**Comment by msoos** [comment]
Beware, the GitHub Actions will break, due to my mess-up. It's just a small issue I'm working to fix.

**Comment by Shatur** [comment]
@msoos, I figured it out. By default CMake uses dynamic runtime but Boost was linked with static runtime. I think this should be a proper fix.
CMake 3.15+ also have [CMAKE_MSVC_RUNTIME_LIBRARY](https://cmake.org/cmake/help/git-stage/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html) property. But since the library also supports an older version, I think that this code can be left, I just changed it a little to avoid the warning about overriding parameters.

**Comment by msoos** [comment]
Amazing work! Once it builds on Appveyor, it'll go in :D Thanks a lot, I owe you a drink/beer if we ever meet :)

Mate

**Comment by andrewvaughanj** [comment]
(I'm keeping an eye on this, and I'll wait for this to go in before looking at why STP is unhappy on Windows -- but maybe *this* is the problem as to why STP is unhappy anyway ...)

**Comment by msoos** [comment]
Yaaay, merged! Thank you!

**Comment by msoos** [comment]
We can now do the same for STP hopefully? :)

**Comment by Shatur** [comment]
> Yaaay, merged! Thank you!

Wow, I'm sorry, I'm no checked everything yet. On CI it passes, of course, but I did not have time to make sure that I got rid of the warning about flag overriding. I'll open another PR :)

> We can now do the same for STP hopefully? :)

Sure, will update my PR for STP once we are done here!

**Pull request merged**
