### PR TITLE
add c wrappers and header

### PR DESCRIPTION
**Pull request by Storyyeller**

### CODE REVIEW

**Comment by msoos** [comment]
You didn't add a license. I'm adding an MIT license because eventually I want to move there. Is that okay?

**Comment by Storyyeller** [comment]
Sure. Sorry about that.

**Comment by Storyyeller** [comment]
P.S. Have you considered Apache v2 instead? From what I've heard, it has better protection against patent litigation.

**Comment by msoos** [comment]
Cool! Thanks, I'll look into it. For the moment, I'll stick with MIT for the files you gave if that's OK!

I'll merge tomorrow when I have more time :) Thanks again!

**Comment by msoos** [comment]
Done! Thanks :) I just fixed it up, we even have the test working, there was a small typo in the definitions for lbool. Thanks again, it's great! Next release will have C bindings, yaaaay!

Mate

**Pull request merged**
