### PR TITLE
support buffer protocol in Solver.add_clauses

### PR DESCRIPTION
**Pull request by fanosta**
This pull request allows Solver.add_clauses to accept any contiguous buffer according to the [Python buffer protocol](https://docs.python.org/3/c-api/buffer.html) instead of just `array.array`. This possibility was already mentioned in #519.

The main advantage of the buffer protocol is that it can be implemented by third party modules as well. Thus, `add_clauses` will also work with numpy arrays for example. Another advantage is that the C side of the API is much simpler, and thus I was able to remove a bunch of code.

One limitation that remains in the current state of this pull request is that only contiguous buffers, i.e., buffers where the element are contiguous in memory, are supported. Non-contiguous buffers can be created in numpy, for example, if someone indexes only a column of a multidimensional array. If that use-case is desired it would not require too many changes to get it running. (Right now, `PyObject_GetBuffer` will automatically raise a ValueError when used on a non-contiguous buffer.)

Regarding unit-tests, I did not add any new ones but the existing ones for `array.array` cover the changed code and they all passed for me.

### CODE REVIEW

**Comment by msoos** [comment]
Nice, thanks so much! I'll let the pipelines pass then I'll merge. Then I'll release a new PIP release :)

Thanks again,

Mate

**Comment by msoos** [comment]
Thanks, merged!

**Comment by fanosta** [comment]
thank you very much :)

**Comment by msoos** [comment]
:) I released a new version. The PyPi build & release should be automatic once the pipeline succeeds. Let me know if it goes wrong or something. Otherwise, it should be fine!

Thanks again,

Mate

**Pull request merged**
