### PR TITLE
Master rust improvements

### PR DESCRIPTION
**Pull request by berke**
- Provide access to set_max_time() to the C and Rust interfaces.
- In Rust interface, derive Debug for Lit and Lbool.

### CODE REVIEW

**Comment by msoos** [comment]
Actually, can you check if this could be merged to msoos/cryptominisat-rs?
I have a new repo with a more good stuff! I think it's easier to build with
Cargo too! Could you please check? If not I'll then merge it myself. Sorry
I wanted to deactivate this one and give a nice notice in the README but I
was waiting for feedback from the original author. Let me know what you
think!

https://github.com/msoos/cryptominisat-rs

**Comment by msoos** [comment]
OK, I hand-merged it to both cryptominisat and cryptominisat-rs :) I will now deleting this rust binding from the main "cryptominisat" repo and the official one will be at:

https://github.com/msoos/cryptominisat-rs

I hope that works for you, right? It's super-easy to use it there, see how caqe uses it:

https://github.com/msoos/caqe/blob/master/Cargo.toml#L8

It's kinda cool, no? So I am removing this subdirectory and instead redirect people to that repo. Would that be OK for you?

Thanks,

Mate

**Comment by msoos** [comment]
Also, I gave you credit in both commits:

https://github.com/msoos/cryptominisat/commit/9af568a69a5da5e11805176926b8db82b08eea25
https://github.com/msoos/cryptominisat-rs/commit/da20b3ac4456c9bfe5153a2e94c1c8ee45356cf7

:)

**Comment by berke** [comment]
Hi, thanks for merging the changes. 

I do have trouble compiling my code with
`cryptominisat = { git = "https://github.com/msoos/cryptominisat-rs", branch= "master" }`
though, it doesn't find the `set_max_time` function at link time:
`cryptominisat.2lxmnjk4-cgu.1:(.text._ZN13cryptominisat6Solver12set_max_time17h65acad2e8d3e0966E+0x5): undefined reference to `cmsat_set_max_time

My code is pretty simple, it simply calls `set_max_time` on a solver.  It compiles with my modifications (before you split out the Rust bindings into its own repo.)  I'm not investigating further in case you know what the issue might be.

**Comment by msoos** [comment]
Ah sorry, I'll check and fix!

Mate

**Comment by msoos** [comment]
I can reproduce this bug. But I have no idea what's going on here. It looks exactly like any other function... are you sure it worked for you before? I literally copy-pasted your code, I double and triple-checked and it's the same thing you wrote. Are you sure your code worked before? There seems to be something off here... Do you know if you could investigate perhaps?

**Comment by msoos** [comment]
I have also added a test to cryptominsiat-rs, so `cargo test` will now fail with the same bug:

```
[....]
 in function `cryptominisat::Solver::set_max_time':
          /[...]/cms-rust/src/lib.rs:178: undefined reference to `cmsat_set_max_time'
          collect2: error: ld returned 1 exit status
```

**Comment by berke** [comment]
Hi Mate,

The new `build.rs` is different as it also builds cryptominisat.  Uncommenting

`println!("cargo:rustc-flags=-L {}/lib", dst.display());`

fixes the issue.

BTW in the README, you should add a line or two reminding the user to git submodule init & update.

Cheers

**Comment by msoos** [comment]
Hi!

Actually, it doesn't solve the issue for me... if I uncomment it, it's still the same :S "cargo test" still fails :( 

Good point on adding info on submodule init&update, I added it! Thanks! Do you have any idea how to fix the `cargo test`, though? Any help would be much appreciated!

**Comment by msoos** [comment]
Hi! I think all of this has been fixed now. Can you please check? The Rust binding is now here: https://github.com/msoos/cryptominisat-rs/ Let me know if it works for you too! Cheers,

Mate

**Pull request closed without merging**
