### PR TITLE
Add functionnalities to the python interface

### PR DESCRIPTION
**Pull request by MPaulmier**
Please see #471 for more details on this PR. This is an ongoing project and some parts still need to be discussed and reworked. 

- [ ] Address the memory issue caused by the added vectors
- [ ] Add tests to the test suite
- [ ] See if there are other problems we didn't think of

You'll see that we did a lot of experiments before finding a good way to generate the different files, it might look a bit messy in the commit messages.

### CODE REVIEW

**Comment by MPaulmier** [comment]
Ok the changes to `cryptominisat.cpp` and `cryptominisat.h.in` shouldn't be in the repo. They're the remains of what we tried to do at the very beginning of this project. Should the responsible commit (30a6069) be reapplied without the changes to these files ? I don't know if that would work with the PR.

**Comment by msoos** [comment]
Some comments:
Here you are changing the indentation. Please don't do that. Please add a commit to fix the indentation.
```
 -    PyObject *clause;
 +	PyObject* clause;
      if (!PyArg_ParseTupleAndKeywords(args, kwds, "O", kwlist, &clause)) {
```


Here you have things indented to different indent even though they are in the sample place logically. Please never do this, **no project will ever accept** a pull request like that. Fix please.
```
PyObject* int_vector_to_list(const std::vector<int> &data) {
 +  PyObject* listObj = PyList_New(data.size());
 +	if (!listObj) PyErr_SetString(PyExc_SystemError, "unable to allocate memory for Python list/");
```
This is *incredibly* inefficient:

```
line.substr(0,1) != std::string("c")
```

What you want is:

```
line[0] != 'c'
```
The above one probably runs about 10x faster. Please be considerate about both memory usage and speed of execution.

**Comment by MPaulmier** [comment]
These commits should fix indentation and code inefficiency.

**Comment by MPaulmier** [comment]
About the memory issue, we're not so sure how to make it better. As you said our solution takes roughly 3x more memory than what we had previously. Taking the clauses directly from the `SATSolver` object isn't an option as far as we know since they will be altered in the process. That's why we went this route. Here are some thoughts we have on this : 

- making the recording of clauses non-mandatory would be a starting point. We would just have to set a flag in the setup function to ask for clause recording;
- we could try and find a better way to store them (other than two vectors of vectors of uint/lit) but this would still take more memory than the current implementation (roughly twice as much if we follow you implementation I would guess);
- we could simply get rid of it and assume the user would build their own file when generating the `Solver` object. In this case, what would be left of our work would be the drat file recovery, the `load` function for loading DIMACS files, the modification of the `setup_solver` function as well as the `nb_clauses` function. These functionnalities shouldn't penalize pycryptosat's performances;

**Comment by msoos** [comment]
Please write the CNF to a temporary file instead of storing it in memory. No need for in-memory storage.

Also, why do we have a DIMACS parser included?

**Comment by MPaulmier** [comment]
Ok this seems like a better idea in terms of memory. We started with that idea in mind and transitionned to the Python object for some reason I can't remember.
The DIMACS parser is required because DRAT-Trim takes a DIMACS file as an input. Since we're in the interface we only have the Python object and getting the drat file wouldn't make sense without this file.

**Comment by msoos** [comment]
We still don't need a parser. We only need to write that DIMACS for DRAT to eat it. No need to parse it.

I still don't much get the point of this whole change request... Apart from providing something that a programmer can do in less than 1 minute (write to a file the clauses while adding them), it provides no effective value to the user, but actually creates a number of real pain points, including coding that doesn't care about user's memory, adding code bloat (DIMACS parser).

In the end, I will have to maintain this which won't be easy as this change provides no effective tests. There is no test that checks that DRAT actually eats the file output. No test that the file is actually DIMACS (header correct, etc), no test that the input clauses are the same as the ones put into DIMACS, etc. Also, XOR clauses cannot be eaten by DRAT, so that's another thing, how is that being handled? This looks like a hack :(

**Comment by msoos** [comment]
I suggest you clean this up, give a rationale, add extensive tests, check with someone if they think it's OK and then create a new pull request! Thanks!

**Pull request closed without merging**
