### PR TITLE
Enhanced bool_switch behaviour

### PR DESCRIPTION
**Pull request by a1880**
bool_switch is now treated as implicited parameter option with implicit value true.
In the help output, bool_switch parameters are shown without arguments

### CODE REVIEW

**Comment by msoos** [comment]
Woow, great work, I like how you are using github!

Note that we can leave notes to each other in the pull request which is pretty nice. Also, if you commit + push to your branch, it will automatically show up in this pull request. That is also pretty neat I think.

I can accept this, or we can just keep this open, and you can keep on working + committing + pushing and we can discuss here. When it's all good, we can merge the whole thing.

In case you are finished with all you wanted to do, let me know and I'll merge.

**Comment by a1880** [comment]
I have now added the fixes wrt the memory leaks. My Valgrind runs resulted in zero errors.
However, I feel a bit uncertain about my destructors and my handling of std::string in general. So, there might be some more bugs lurking.

**Comment by a1880** [comment]
What is missing is the code beautification (replacing tabs with 4 spaces).
Some of your other remarks I probably have not fully understood.
I have written my fixes under Ubuntu Linux. It would help to install a proper debugger with GUI.
gdb and ddd seem a bit awkward compared to Visual Studio. Any suggestions?

**Comment by msoos** [comment]
Cool! Unfortunately, we have this issue now

```
$ ./cryptominisat4 --zero-exit-status mizh-md5-47-3.cnf.gz 
c Outputting solution to console
c CryptoMiniSat version 4.5.3
c CryptoMiniSat SHA revision 518e47389b61dc6e9b36517a959972ae7f21cb9d
c CryptoMiniSat compilation env CMAKE_CXX_COMPILER = /usr/lib/ccache/c++ | CMAKE_CXX_FLAGS =  -std=c++11 -pthread -g -Wall -Wextra -Wunused -pedantic -Wsign-compare -Wtype-limits -Wuninitialized -Wno-deprecated -Wstrict-aliasing -Wpointer-arith -fvisibility=hidden -Wpointer-arith -Wformat-nonliteral -Winit-self -Wparentheses -Wunreachable-code -ggdb3 -fPIC | COMPILE_DEFINES =  -DBOOST_TEST_DYN_LINK -DSLOW_DEBUG -DUSE_ZLIB -DUSE_VALGRIND -DUSE_M4RI | STATICCOMPILE = OFF | ONLY_SIMPLE =  | Boost_FOUND = 1 | TBB_FOUND =  | STATS = OFF | MYSQL_FOUND =  | SQLITE3_FOUND =  | ZLIB_FOUND = TRUE | VALGRIND_FOUND = TRUE | ENABLE_TESTING = ON | M4RI_FOUND = TRUE | SLOW_DEBUG = ON | PYTHON_EXECUTABLE =  | PYTHON_LIBRARY =  | PYTHON_INCLUDE_DIRS =  | MY_TARGETS =  | compilation date time = Oct 14 2015 22:51:17
c compiled with gcc version 4.9.2
c Executed with command line: ./cryptominisat4 --zero-exit-status mizh-md5-47-3.cnf.gz
c Reading from standard input... Use '-h' or '--help' for help.
```

In other words, the bool switch now eats the next argument, which it shouldn't :(

**Comment by msoos** [comment]
Also, getopt_long.cpp has this:

```
 All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *  This product includes software developed by the University of
 *  California, Berkeley and its contributors.
```

I will not display that on every single page about CryptoMiniSat. That is _way_ too intrusive.

**Comment by a1880** [comment]
Yes, I'll try to fix the bool_switch flaws asap. It definitely needs more testing.
Can you explain to me why the Travis tests are failing? Can I do these tests on my own?

The slow solution time is caused by the polarity calculation. If I add "--polar=false", it solves my default example right away as it used to to before.

**Comment by a1880** [comment]
It seems to be common practice of software which makes use of getopt_long to leave the

header comments as is and omit any further display.

getopt_long is part of many packages including Android. I have never seen any note of it

in advertisements.

 

Von: Mate Soos [mailto:notifications@github.com] 
Gesendet: Mittwoch, 14. Oktober 2015 23:58
An: msoos/cryptominisat
Cc: Axel Kemper
Betreff: Re: [cryptominisat] Enhanced bool_switch behaviour (#284)

 

Also, getopt_long.cpp has this:

 All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *  This product includes software developed by the University of
 *  California, Berkeley and its contributors.

I will not display that on every single page about CryptoMiniSat. That is way too intrusive.

**Pull request merged**
