### PR TITLE
Update, fix compilation of main_emscripten.cpp

### PR DESCRIPTION
**Pull request by MingweiSamuel**
Wasn't compiling, seems it was left behind with later updates. Not sure about removing `print_model`.

I'm hoping to get a proper wasm/js/ts interface going soon, let me know what you think.

### CODE REVIEW

**Review by msoos — CHANGES_REQUESTED** [review]
Hi! Great catch, thanks :) However, the `print_model()` I believe is needed. Can you please remove that change? Then I'd be happy to merge! :) Thanks again, great stuff!

Mate

**Comment by MingweiSamuel** [comment]
Sure, for now I made `MainCommon::print_model` static so it can be called from main_emscripten.

I'm planning on making full [embind bindings](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html) for all the regular stuff in the [incremental api](https://github.com/msoos/cryptominisat#incremental-library-usage) since I'll need those (and a way to get the solution model) in my webapp. So those will supersede the existing c functions (`cstart_solve` `ccontinue_solve` `cget_num_conflicts`). I can keep them around for backwards compatibility or just also submit a PR to update https://github.com/msoos/cryptominisat_web once they're implemented.

I also noticed the wasm file jumped to 17mb in size, are there new build flags that should be set for the build?
I am using these:
```
emcmake cmake -DENABLE_PYTHON_INTERFACE=OFF -DNOM4RI=ON \
    -DENABLE_TESTING=OFF -DNOZLIB=ON -DONLY_SIMPLE=ON \
    -DEMSCIPTEN=ON \
    ..
```

**Comment by MingweiSamuel** [comment]
Actually I guess we can just use the C apis, that's probably a better option.

**Comment by msoos** [comment]
Hey!

Wow, thanks for the fixes! The jump in size is a bit weird, though. I build with what's under `scripts` (if you pull the submodules, this directory appears). It has the following text:

```
#!/bin/bash

set -e

rm -rf cm* CM* lib* cryptomini* Testing* tests* pycryptosat include tests cusp* scalmc*
cmake -DENABLE_PYTHON_INTERFACE=OFF -DNOM4RI=ON \
    -DENABLE_TESTING=OFF -DNOZLIB=ON -DONLY_SIMPLE=ON \
    -DEMSCIPTEN=ON \
    -DCMAKE_TOOLCHAIN_FILE=/home/soos/development/emsdk/emscripten/1.38.0/cmake/Modules/Platform/Emscripten.cmake \
    ..
make VERBOSE=1 -j4
```

But yeah, the C interface is well-tested and used by many, so it should be clean! :)

Let me know if the above helped. Also, let me know how you are planning to package it, kinda cool that you are using the javascript version!

**Comment by MingweiSamuel** [comment]
Yeah I've written a very thin typescript wrapper for it here: https://github.com/SudokuStudio/SudokuStudio/tree/main/packages/cryptominisat  
I plan on putting it in its own repo, polishing it up, and releasing it as an NPM package eventually.

Also needed pseudo-boolean constraints so we compiled pblib to wasm also: https://github.com/SudokuStudio/pblib-wasm

We're using it for this WIP sudoku solving/setting website, [here's an example](https://www.sudokustudio.net/?f=N4IgzglgXgpiBcBOANCALhNAbO8QGEsIAHYmAExFQEMBXNACwHsAnBEABQYiNIAIAQlloBbGH2oBranwDmwkQH1upJlRAtaOMDDTsAyrXJNJtPgFo+MAG4wWATz4smAd2R8AxkwUA7d9R9yPgBmAA9gvgAjJlC+EVowNE8mHzRqCB8JLCw+RnFyCFlMMD4AM2cRPgBGc0QAOj59JjE+AqK0EuoWcWosbupyRyLbHzqAHR8JgEFUiHMAaQzZCysAR1pe1sLiuOpHHyYktCZaDwYt6lkU3qx7ccmfABUGOxFm3TsVtp34xL5ElgQDzYRwZDz9HRlCpRLSRXJMXIke7TFjOFwrPKeCAsDw4ILfJJeHyJTD0GAlTFgUR8JilXIvLbtTpYFLLTFdNH3dSyQGUeAAbX5wAAvsgRWLReKpZKZRKALrIIWy6US1UqkUKpVq5Ugay9Wi4ABsqGGMB8CDQmhgyptmvVNu12rtOr1wlwAFYTRARharS79bgql6ffBLQb/W6EAAWYNm33hp2K+2O5MapMOqW6gMIYKx82hv0pmXOoul6Ul1MZ4sKkABDCSJbxmCoPIsN5iNB2BBCkBEHzk7v8kAAJUN+Hd6mHAHZ8FHJwAOfDBBf4ABMIDlcslvYyA4FQ+H7rXk6jS8nwVnk9Xl83277e8FI9PE9Qw4vhqv+Cnn/nG63Yp3fswEHEcj1/V8x2/V8Zw/V9Fw/W8aw5Vxu1Ae9gP3UDL1fU9l1fC911fa9103VAPBgbIMIPI853/NDdyo6j8FgkdIMnGdwJHRdf1IkByMo7ssIQu8GJA4dFxfEcZznCCz1kkia34rAqK48cNxEoCxOvSS32Yk8v30njFIo5TBOHbT1IA9CxJnPDVJkkdEDU3ilJU6czy3LcgA=). Solutions and some SAT input info prints in the console, and the solver is working really well.

Thanks for the great project :)

**Comment by msoos** [comment]
Wow, an NPM package would be effin' amazing! I really am too old school for this :D It'd be really cool.

And the website looks really fun too! By the way, with our tool [ApproxMC](https://github.com/meelgroup/approxmc), or [GANAK](https://github.com/meelgroup/ganak), you could also (approximately/exactly) count the number of solutions :) That can be kinda fun, I think. Beware that you likely need projected counting, so ApproxMC may be a better solution. Projected counting is when you want to know how many solutions are that differ on variables e.g. 3, 4, and 10 (i.e. max 2**3 solutions) rather than over all variables (so-called unprojected counting). Since you likely have many variables that are uninteresting (just helper variables), you probably want to count over only a subset of variables.

**Comment by MingweiSamuel** [comment]
Oh sweet I'll definitely have to try that out, I had no idea something like that existed. Projected counting sounds right. Thanks again, it's great to see such a well maintained set of research projects :D

**Pull request merged**
