### PR TITLE
typos

### PR DESCRIPTION
**Pull request by dennis714**

### CODE REVIEW

**Comment by a1880** [comment]
While you are at it:
The plural of matrix is actual [matrices](https://www.google.de/search?q=matrixes+matrices) rather than matrixes.

**Comment by msoos** [comment]
Both matrixes and matrices are correct. Please look at the dictionaries online or offline. Here is one:

http://www.dictionary.com/browse/matrix?s=t

Oxford dictionary will say the same. So will the American Heritage. Both are correct.

**Comment by msoos** [comment]
Thanks for the typos fixes!! Really good stuff :) Merged, thanks!

**Comment by a1880** [comment]
Well, I don't want to fight for matrices, but the Google hit count speaks a clear language: 40mio vs 400k

**Pull request merged**
