### PR TITLE
Enable W4 when compiling with MSVC

### PR DESCRIPTION
**Pull request by horenmar**
Also fixes most of the resulting warnings. There are some 30 warnings
left, but they should be easy to fix with some mechanical work.

### CODE REVIEW

**Comment by horenmar** [comment]
The `Lit l` changes are there to remove variable shadowing warnings, as those scopes already had `Lit lit` previously declared. Same goes for the other small mechanical changes.

> /W4 may spit out WAAAAY too many warnings. I had at one time >100MB of warnings.... I am afraid. I will never be able to wade through that. Why do we need /W4? I am really afraid.

As mentioned, after the changes and using VS2017, only ~30 warnings are left and they are mostly mechanical in nature (and if solverconf.h was sanitized, there should be even less). The three biggest offenders were "stl in DLL exported function", which I decided to turn off project-wide, "constant expression in an if" caused by `release_assert(false, ...)` and ton of "assignment in an if" in the simple main, which got turned off for that file.

As to the reason it is needed, /W4 is needed for roughly the same reason that -Wall -Wextra is needed. It is a fairly reasonable set of warnings to tell you when you are doing something fishy.

**Comment by msoos** [comment]
Ah, cool, makes sense :) Thanks! I'll merge tonight :) Thanks again!

**Comment by msoos** [comment]
I get 4000+ lines of warnings in AppVeyor, please see

https://ci.appveyor.com/project/msoos/cryptominisat/build/1.0.396

This is really ugly, I want to be able to work with this, and warnings that are never resolved will not be useful, just clutter everything up. Do you know how to fix them? Can you please pull in a merge request that fixes it or pulls down the warning level please! Help would really be appreciated :) Thanks!

**Comment by msoos** [comment]
I have created a new issue, here: https://github.com/msoos/cryptominisat/issues/419

**Comment by horenmar** [comment]
Quick check of the log says that most of the warnings are reported over and over and over again, as they are caused by code in headers...

I'll throw up a PR to reduce them somewhat soon.

**Pull request merged**
